version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
